language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.5
deploy:
  provider: npm
  email: npm@cozycloud.cc
  skip_cleanup: true
  api_key:
    secure: ClGFyibVA3QxWlQPmIZhnOGOCY4r9YzPuVE8CcwvG8I11upDSuwJ5YRNF/i8bG3AbtKgcX4vHeu6fTZ936MNxoA+HcVVTlM2XMAaZoFnVBG0tUKuHe1qg7n+cVQlDvuEvln4t2yDGwq1fvlsljmT/YyvvQ28ffB++OSb9xHky/u6stmY8xquPbJ9vusF/jap8YzeIAz537z7sqHPz782Fg+hdbcLv0Dy8IQx+8KE/e1kPLutsznPDeVANpKU87k0HXHNzJzeH/8mbuap19Io4dvqhNPIyQ2zDsFpQhPwUrrevfizyClZuvaxwwNAxg1fK3InV3Y3Z8JsxM8HZdKs5v+qvHC8cHuhSJ/Cb2jr3Sod2sc/+fxnQ5ox3tdpOD1UeLCktI8E0V86nqDwSU/yW7b09QMfot0a5WQUru0hHgSY/uwgx/BKkBTMsu0VhUzQMUDrmQX+FpYyojTOw17dqw5GozYEpHZ5t0znQ0GUoA/qO2e3o9EV+zcpfe6DBYDxQx1b4U7GPYwUK8QWOuKv4mVtyUlzBdDinVxZ4l1ST34/+OBCGHsZglL/5l6Kq0NCIONU/vr8ZHx5wqKYwI5qRKp2+BnfHbsHnQ2WHEdSFaOL/0g0n0Z9V0KHNfIWKzNHYRlHrMLcZ/bGf+Eh+g4gH2Eue8ELF5Xq3rkgPsTXhLk=
  on:
    tags: true
    repo: cozy/cozy-bar
before_deploy:
- touch .npmignore
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWORD" >> ~/.transifexrc
env:
  global:
    secure: ESL2AFj2ER9Smf+BsInpq7/Q0Z3LWbvwzgbCd4S4XxVCU8XM17aKYf+3ypRe0djxsezqX48RKF5DBTZWNNrb0/ey8/saNlBw7FDafi6kkxtTl8j2wvOwkLmqnVFSzj3P5f8jfmFPPbjy1Myzw8q8nkeg68iS+vCc86P8PeOjlFqifNcb7dnM+EBH8FmYk78pUkBo62dn16RlqpdcSh1f1Ywa/kXkgl+hmjnkcLz6W8FYG2H9fveixK/uMFtXeQ4SXMobNh5KGwFNi9jbyOcwVHUMp3h1W8qPXM9J4It5MUvmFRprjDl7xX58TzpGzCdzqezVOG7CgZd8DCOTgroakRtqWBOctf+oWVqplP8N4+pggYyRcbQdv7CXdOm/3K+relR/MKB6QeQ2Iey2FI/v73CcvAi60bJM8plsV/GogTT39jGLzbjGL5WZPr+gIMshKtiEXD5mt9kq/hdJS1heSg/F9Eh2Rtluo+3rgSNfbm2XdMDmHXeZT1Z5vCoY+ekKhfqrIYt//DrH1+QAPl5WL3nJSDz/b9S4GM1G/3ZptxGYt99hzm9NSTfCGHIlhUcJs2qDENWM14HRVhjKoh8MPo5NeVpT2nLAsNGYA9iW4lZMxDRBcV1hsdA9JHj8MCKINldp9Mr0qHRYR7NrSuThU5iZW1C4IwbLYNzF+A/tqd4=
