actions:
    - slug: desktop
      icon: icon-laptop.svg

    - slug: mobile
      icon: icon-phone.svg

    - slug: cozy-collect
      icon: icon-bills.svg

    - slug: support
      icon: icon-question-mark.svg
