settings:
  -
    - slug: profile
      href: /profile
    - slug: connectedDevices
      href: /connectedDevices
  -
    - slug: storage
      component: storage
      currentDiskUsage: null
  -
    - slug: help
      external: true
      href: https://docs.cozy.io/
    - slug: email
      href: mailto:contact@cozycloud.cc
  -
    - slug: logout
      href: /logout
apps: []
