subsections:
  settings:
    - slug: profile
      href: /profile
    - slug: connectedDevices
      href: /connectedDevices
  help:
    - slug: help
      external: true
      href: https://mesinfos.fing.org/forum
  logout:
    - slug: logout
      action: logout
  beta:
    - slug: beta_status
      inactive: true

components:
  storage:
    slug: storage
    component: storage
    currentDiskUsage: null

settings:
  - _.subsections.settings
  -
    - _.components.storage
  - _.subsections.help
  - _.subsections.logout
  - _.subsections.beta

apps: []

sections:
  bar:
    - slug: apps
      icon: icon-cube
      async: true
      items: _.apps
      categorized: true
    - slug: settings
      icon: icon-cog
      items: _.settings
  drawer:
    - _.subsections.settings
    - _.subsections.help
    - _.subsections.logout
    - _.subsections.beta
