subsections:
  settings:
    - slug: profile
      href: /profile
    - slug: connectedDevices
      href: /connectedDevices
  help:
    - slug: help
      external: true
      href: https://docs.cozy.io/
    - slug: email
      href: mailto:contact@cozycloud.cc
  logout:
    - slug: logout
      action: logout

components:
  storage:
    slug: storage
    component: storage
    currentDiskUsage: null

settings:
  - _.subsections.settings
  -
    - _.components.storage
  - _.subsections.help
  - _.subsections.logout

apps: []

sections:
  bar:
    - slug: apps
      icon: icon-cube
      async: true
      items: _.apps
    - slug: settings
      icon: icon-cog
      items: _.settings
  drawer:
    - _.subsections.settings
    - _.subsections.help
    - _.subsections.logout
